import type { TaskPayload } from "../core";
import { formatDuration, round2, formatCompact, getPath, setPath } from "./utils";

export type BenchmarkReport = TaskPayload;

interface AvgField {
    path: string;
    round: (value: number) => number;
}

const AVG_FIELDS: AvgField[] = [
    { path: "duration_ms", round: Math.round },
    { path: "total_ms", round: Math.round },
    { path: "active_ms", round: Math.round },
    { path: "idle_ms", round: Math.round },
    { path: "idle_gap_count", round: Math.round },
    { path: "metrics.clicks.total", round: Math.round },
    { path: "metrics.clicks.ceremonial", round: Math.round },
    { path: "metrics.clicks.wasted", round: Math.round },
    { path: "metrics.target_effort.average_id", round: round2 },
    { path: "metrics.scroll.total_px", round: Math.round },
    { path: "metrics.scroll.page_px", round: Math.round },
    { path: "metrics.scroll.container_px", round: Math.round },
    { path: "metrics.scroll.horizontal_px", round: Math.round },
    { path: "metrics.cursor.total_px", round: Math.round },
    { path: "metrics.cursor.move_events", round: Math.round },
    { path: "metrics.input.context_switches", round: Math.round },
    { path: "metrics.input.longest_keyboard_streak", round: Math.round },
    { path: "metrics.input.longest_mouse_streak", round: Math.round },
    { path: "metrics.input.shortcuts_used", round: Math.round },
];

export function buildAveragedReport(runs: BenchmarkReport[]): BenchmarkReport {
    const validRuns = runs.filter((run) => run?.schema_version === "3.0" && run.metrics);
    if (validRuns.length === 0) throw new Error("No valid runs");

    const baseReport = JSON.parse(JSON.stringify(validRuns[validRuns.length - 1])) as BenchmarkReport;
    const count = validRuns.length;

    for (const field of AVG_FIELDS) {
        const sum = validRuns.reduce((total, run) => total + getPath(run, field.path), 0);
        setPath(baseReport, field.path, field.round(sum / count));
    }

    const hardestRun = validRuns.reduce((best, run) =>
        run.metrics.target_effort.max_id > best.metrics.target_effort.max_id ? run : best,
    );
    baseReport.metrics.target_effort.max_id = hardestRun.metrics.target_effort.max_id;
    baseReport.metrics.target_effort.max_distance_px = hardestRun.metrics.target_effort.max_distance_px;
    baseReport.metrics.target_effort.max_target_width_px = hardestRun.metrics.target_effort.max_target_width_px;

    baseReport.run_count = count;
    baseReport.averaged = true;
    return baseReport;
}

export function generateMarkdownReport(report: BenchmarkReport): string {
    const lines: string[] = [];
    const m = report.metrics;

    lines.push("# UX Bench Task Report");
    lines.push("");
    lines.push(`**App:** ${report.app}`);
    lines.push(`**Task:** ${report.task_id}`);
    lines.push(`**Task Run:** ${report.task_run_id}`);
    lines.push(`**Status:** ${report.status}`);
    if (report.run_count && report.run_count > 1) lines.push(`**Runs:** ${report.run_count} (averaged)`);
    lines.push(`**Duration:** ${formatDuration(report.duration_ms)}`);
    lines.push("");

    lines.push("## Metrics");
    lines.push("");
    lines.push("| Metric | Value | Detail |");
    lines.push("|--------|-------|--------|");
    lines.push(
        `| Time | ${formatDuration(report.total_ms)} | ${formatDuration(report.active_ms)} active, ${formatDuration(report.idle_ms)} idle |`,
    );
    lines.push(`| Idle Gaps | ${report.idle_gap_count} | pauses over threshold |`);
    lines.push(`| Clicks | ${m.clicks.total} | ${m.clicks.ceremonial} ceremonial, ${m.clicks.wasted} wasted |`);
    lines.push(
        `| Target Effort | ${round2(m.target_effort.average_id)} avg ID | max ${round2(m.target_effort.max_id)}, ${Math.round(m.target_effort.max_distance_px)}px distance |`,
    );
    lines.push(
        `| Cursor | ${formatCompact(Math.round(m.cursor.total_px))}px | ${m.cursor.move_events} movement samples |`,
    );
    lines.push(
        `| Scroll | ${formatCompact(Math.round(m.scroll.total_px))}px | ${Math.round(m.scroll.page_px)} page, ${Math.round(m.scroll.container_px)} container |`,
    );
    lines.push(
        `| Switches | ${m.input.context_switches} | longest keyboard ${m.input.longest_keyboard_streak}, longest mouse ${m.input.longest_mouse_streak} |`,
    );
    lines.push(`| Shortcuts | ${m.input.shortcuts_used} | modifier-key combos |`);
    lines.push("");
    lines.push("---");
    lines.push(`*Generated by UX Bench on ${new Date().toLocaleString()}*`);

    return lines.join("\n");
}
